
name: testing pipeline

on:
  push:
    branches:
      - master

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      -
        name: step 1
        run: echo "Say hello world. this is our first pipeline"